---
title: "RWEBRIDGE-CHEKCER report"
author: "RWEBRIDGE-CHEKCER"
date: "`r format(Sys.time(), format = '%Y-%m-%d T %H:%M:%S')`"
output: html_document
params: 
    output_dir: NULL
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

This document reports the results of content check for tables uploaded by user, 
based on json schema file in "inst/extdata/RWEBRIDGE_schema.json"

## Results

Passed/Failed information with additional notes
```{r display_results, echo=FALSE}
if (!is.null(params$output_dir)){
  # Read and combine results from output directory
  list_of_files <- list.files(params$output_dir)
  format_table_path <- list_of_files[grep("format_table.csv",list_of_files)]
  relation_table_path <- list_of_files[grep("realtion_table.csv",list_of_files)]

  if (length(format_table_path) != 0){
    format_table <- read.csv(paste(params$output_dir, format_table_path, sep = "/"),
                             stringsAsFactors = F,
                             na.strings = c(""))
    
    format_table <- read.csv(paste(params$output_dir, relation_table_path, sep = "/"),
                             stringsAsFactors = F,
                             na.strings = c(""))

    }
    x_html <- kableExtra::kable(
        format_table,
        format = "html",
        escape = FALSE
        )
    kableExtra::kable_styling(x_html, 
                    bootstrap_options = "bordered",
                    full_width = FALSE)
    
    x_html <- kableExtra::kable(
        relation_table,
        format = "html",
        escape = FALSE
        )
    kableExtra::kable_styling(x_html, 
                    bootstrap_options = "bordered",
                    full_width = FALSE)
  }
  



```

